name: "Check i18n duplicates"
description: "Check and list all of i18n keys has same value"
inputs:
  file: # id of input
    description: "i18next file to check"
    required: true
    default: "src/i18n/locales/en-US.json"
runs:
  using: "node16"
  main: "dist/index.js"
