name: "Check i18n duplicates"
description: "Check and list all of i18n keys has same value"
inputs:
  file: # id of input
    description: "i18next file to check"
    required: true
    default: "src/i18n/locales/en-US.json"
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  repository:
    description: 'The full name of the repository in which to create or update a comment.'
    default: ${{ github.repository }}
runs:
  using: "node16"
  main: "dist/index.js"
